export const theme = {
    colors: {
      primary: '#9DD8B7',
      secondary: '#4A9E78',
      background: '#E5F6EB',
      accent: '#F5F5DC',
      cardBackground: '#FFFFFF',
      text: '#333333',
      textSecondary: '#666666',
      textLight: '#999999',
      white: '#FFFFFF',
      white80: 'rgba(255, 255, 255, 0.8)',
      chart: {
        primary: '#9DD8B7',
        secondary: '#D0E6CC',
        accent: '#F5D6BA',
        blue: '#6ECFF6',
        yellow: '#F9E79F',
        green: '#82C595',
        gray: '#E0E0E0',
      }
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
      xxl: 48,
    },
    borderRadius: {
      sm: 4,
      md: 8,
      lg: 16,
      xl: 24,
      full: 9999,
    },
    fontSizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      title: 28,
    },
    shadows: {
      small: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
      },
      medium: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 3,
      },
      large: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
      },
    },
    months: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
  };